// GENERATED by scripts/gen-hko-station-names.mjs — do not edit by hand.
// Source: https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=rhrread&lang={en,tc}
// Generated: 2026-09-17 · 27 stations

/** HKO's English station name -> its Chinese name. The English name is the
 *  identity key everywhere (see stationCodes.ts); this is display only. */
export const HKO_STATION_NAMES_TC: Readonly<Record<string, string>> = Object.freeze({
  'Chek Lap Kok': '赤鱲角',
  'Cheung Chau': '長洲',
  'Happy Valley': '跑馬地',
  'Hong Kong Observatory': '香港天文台',
  'Hong Kong Park': '香港公園',
  'Kai Tak Runway Park': '啟德跑道公園',
  "King's Park": '京士柏',
  'Kowloon City': '九龍城',
  'Kwun Tong': '觀塘',
  'Lau Fau Shan': '流浮山',
  'Sai Kung': '西貢',
  'Sha Tin': '沙田',
  'Sham Shui Po': '深水埗',
  'Shau Kei Wan': '筲箕灣',
  'Shek Kong': '石崗',
  'Stanley': '赤柱',
  'Ta Kwu Ling': '打鼓嶺',
  'Tai Mei Tuk': '大美督',
  'Tai Po': '大埔',
  'Tseung Kwan O': '將軍澳',
  'Tsing Yi': '青衣',
  'Tsuen Wan Ho Koon': '荃灣可觀',
  'Tsuen Wan Shing Mun Valley': '荃灣城門谷',
  'Tuen Mun': '屯門',
  'Wong Chuk Hang': '黃竹坑',
  'Wong Tai Sin': '黃大仙',
  'Yuen Long Park': '元朗公園',
})
