// GENERATED by scripts/gen-hk-holidays.mjs — do not edit by hand.
// Source: https://www.1823.gov.hk/common/ical/en.json
// Generated: 2026-09-16 · 51 holidays, 2025–2027
// Re-run annually: next year's holidays are gazetted each May.

/** Local 'yyyy-MM-dd' -> official English holiday name. */
export const HK_HOLIDAYS: Readonly<Record<string, string>> = Object.freeze({
  '2025-01-01': "The first day of January",
  '2025-01-29': "Lunar New Year’s Day",
  '2025-01-30': "The second day of Lunar New Year",
  '2025-01-31': "The third day of Lunar New Year",
  '2025-04-04': "Ching Ming Festival",
  '2025-04-18': "Good Friday",
  '2025-04-19': "The day following Good Friday",
  '2025-04-21': "Easter Monday",
  '2025-05-01': "Labour Day",
  '2025-05-05': "The Birthday of the Buddha",
  '2025-05-31': "Tuen Ng Festival",
  '2025-07-01': "Hong Kong Special Administrative Region Establishment Day",
  '2025-10-01': "National Day",
  '2025-10-07': "The day following the Chinese Mid-Autumn Festival",
  '2025-10-29': "Chung Yeung Festival",
  '2025-12-25': "Christmas Day",
  '2025-12-26': "The first weekday after Christmas Day",
  '2026-01-01': "The first day of January",
  '2026-02-17': "Lunar New Year’s Day",
  '2026-02-18': "The second day of Lunar New Year",
  '2026-02-19': "The third day of Lunar New Year",
  '2026-04-03': "Good Friday",
  '2026-04-04': "The day following Good Friday",
  '2026-04-06': "The day following Ching Ming Festival",
  '2026-04-07': "The day following Easter Monday",
  '2026-05-01': "Labour Day",
  '2026-05-25': "The day following the Birthday of the Buddha",
  '2026-06-19': "Tuen Ng Festival",
  '2026-07-01': "Hong Kong Special Administrative Region Establishment Day",
  '2026-09-26': "The day following the Chinese Mid-Autumn Festival",
  '2026-10-01': "National Day",
  '2026-10-19': "The day following Chung Yeung Festival",
  '2026-12-25': "Christmas Day",
  '2026-12-26': "The first weekday after Christmas Day",
  '2027-01-01': "The first day of January",
  '2027-02-06': "Lunar New Year's Day",
  '2027-02-08': "The third day of Lunar New Year",
  '2027-02-09': "The fourth day of Lunar New Year",
  '2027-03-26': "Good Friday",
  '2027-03-27': "The day following Good Friday",
  '2027-03-29': "Easter Monday",
  '2027-04-05': "Ching Ming Festival",
  '2027-05-01': "Labour Day",
  '2027-05-13': "The Birthday of the Buddha",
  '2027-06-09': "Tuen Ng Festival",
  '2027-07-01': "Hong Kong Special Administrative Region Establishment Day",
  '2027-09-16': "The day following the Chinese Mid-Autumn Festival",
  '2027-10-01': "National Day",
  '2027-10-08': "Chung Yeung Festival",
  '2027-12-25': "Christmas Day",
  '2027-12-27': "The first weekday after Christmas Day",
})

/** Years the bundled table actually covers. Outside this range the calendar
 *  shows no holidays, which means "unknown", not "none". */
export const HK_HOLIDAY_YEARS = Object.freeze({
  first: 2025,
  last: 2027,
})
